short_names = ['Chris', 'Hank', 'Joel']
short_names.append('Bruce')
print(short_names)
short_names.pop(3)
print(short_names)
short_names.append('Rusty')
print(short_names)
short_names.remove('Rusty')
print(short_names)
print(short_names[0])
print(short_names[1])
print(short_names[2])
